"""
Static site content: profile, translations, experience, education.

Previously these lived as module-level constants in app.py, mixed in with
route definitions and app wiring. They are content, not application code, so
they are isolated here.

EXPERIENCES and EDUCATION gained a `stack` list: every reference portfolio
reviewed tags each role with the technologies used in it, which is both what
a reader scans for and what makes the page findable by keyword. The previous
free-text `desc` alone carried none of that signal.
"""

PROFILE = {
    "name": "امیرحسین نعیمائی",
    "name_en": "Amirhossein Naeimaei",
    "job": "توسعه‌دهنده بک‌اند (Python/Flask)",
    "job_en": "Backend Developer (Python/Flask)",
    "location": "مازندران، ایران",
    "location_en": "Mazandaran, Iran",
    "email": "amirhossein.naimaei81@gmail.com",
}

SITE_TITLE = "رزومهٔ من"
NAME = "امیرحسین نعیمائی"
TAGLINE = "توسعه‌دهندهٔ بک‌اند | Flask | Python"
LOCATION = "نوشهر"
CONTACT_EMAIL = "amirhossein.naimaei81@gmail.com"


TRANSLATIONS = {
    "fa": {
        "SITE_TITLE": "رزومهٔ من",
        "NAME": "امیرحسین نعیمائی",
        "TAGLINE": "توسعه‌دهندهٔ بک‌اند | Flask | Python",
        "META_DESCRIPTION": (
            "رزومه و نمونه‌کارهای امیرحسین نعیمائی، توسعه‌دهندهٔ بک‌اند "
            "پایتون با تمرکز بر Flask، طراحی API و پایگاه داده."
        ),
        "MENU_HOME": "خانه",
        "MENU_PROJECTS": "پروژه‌ها",
        "MENU_ABOUT": "درباره‌من",
        "MENU_ARTICLES": "مقالات",
        "MENU_CONTACT": "تماس",
        "BTN_RESUME": "دانلود رزومه",
        "BTN_PROJECTS": "مشاهدهٔ پروژه‌ها",
        "CONTACT_TITLE": "تماس با من",
        "CONTACT_NAME": "اسم",
        "CONTACT_EMAIL": "ایمیل",
        "CONTACT_MSG": "پیام",
        "CONTACT_SEND": "ارسال",
        "CONTACT_CLEAR": "پاک کردن",
        "MSG_SUCCESS": "پیام شما با موفقیت ارسال شد!",
        "MSG_ERROR": "لطفاً همهٔ فیلدها را پر کنید.",
        "LOCATION": "نوشهر",
        "SKILLS_TITLE": "مهارت‌ها",
        "VIEWS": "بازدید",
        "EXPERIENCE_TITLE": "تجربهٔ کاری",
        "EDUCATION_TITLE": "تحصیلات",
        "ERR_404_TITLE": "صفحه پیدا نشد",
        "ERR_404_BODY": "آدرسی که دنبالش بودید وجود ندارد یا جابه‌جا شده است.",
        "HERO_GREETING": "سلام، من",
        "HERO_SUFFIX": "هستم.",
        "HERO_ROLE": "متخصص IT و توسعه‌دهنده نرم‌افزار",
        "HERO_INTRO": "در زمینه توسعه نرم‌افزار، زیرساخت IT، شبکه و سیستم‌های اطلاعاتی فعالیت می‌کنم و روی ساخت راهکارهای کاربردی و قابل توسعه تمرکز دارم.",
        "FOOTER_BIO": "توسعه‌دهنده نرم‌افزار و متخصص IT، علاقه‌مند به طراحی سیستم‌های کاربردی، شبکه و فناوری‌های نوین.",
        "STATUS_AVAILABLE": "آماده همکاری",
        "QUICK_LINKS": "دسترسی سریع",
        "CONNECT": "ارتباط با من",
        "STAT_PROJECTS": "پروژه",
        "STAT_ARTICLES": "مقاله",
        "STAT_SKILLS": "مهارت",
        "FEATURED_PROJECTS": "پروژه‌های منتخب",
        "LATEST_ARTICLES": "آخرین مقالات",
        "VIEW_ALL": "مشاهده همه",
        "PRIVATE_PROJECT": "پروژه خصوصی",
        "READ_ARTICLE": "مطالعه مقاله",
        "NO_PROJECTS_YET": "هنوز پروژه‌ای ثبت نشده است.",
        "NO_ARTICLES_YET": "هنوز مقاله‌ای منتشر نشده است.",
        "NO_PROJECTS_TITLE": "پروژه‌ای موجود نیست",
        "NO_PROJECTS_BODY": "هنوز پروژه‌ای برای نمایش ثبت نشده است.",
        "CTA_TITLE": "پروژه‌ای در ذهن داری؟",
        "CTA_BODY": "اگر درباره یک پروژه، همکاری یا موضوع فنی می‌خواهی صحبت کنیم، از طریق صفحه تماس با من در ارتباط باش.",
        "BACK_TO_PROJECTS": "بازگشت به پروژه‌ها",
        "STATUS_COMPLETED": "تکمیل شده",
        "STATUS_IN_PROGRESS": "در حال توسعه",
        "STATUS_PLANNED": "برنامه‌ریزی شده",
        "ABOUT_PROJECT": "درباره پروژه",
        "KEY_FEATURES": "قابلیت‌های اصلی",
        "PROJECT_INFO": "اطلاعات پروژه",
        "LABEL_YEAR": "سال",
        "LABEL_STATUS": "وضعیت",
        "TECHNOLOGIES": "تکنولوژی‌ها",
        "SOURCE_CODE": "سورس پروژه",
        "VIEW_ON_GITHUB_SHORT": "مشاهده در GitHub",
        "LANG_FA": "فارسی",
        "LANG_EN": "انگلیسی",
        "ERR_429_TITLE": "درخواست بیش از حد",
        "ERR_429_BODY": "تعداد درخواست‌های شما بیش از حد مجاز بوده است. لطفاً کمی بعد دوباره تلاش کنید.",
        "ERR_500_TITLE": "خطای سرور",
        "ERR_500_BODY": "مشکلی از سمت ما پیش آمد. لطفاً بعداً دوباره تلاش کنید.",
        "ERR_HOME": "بازگشت به خانه",
        "SKILL_CAT_LANGUAGES": "زبان‌ها",
        "SKILL_CAT_FRAMEWORKS": "فریم‌ورک‌ها",
        "SKILL_CAT_DATABASES": "پایگاه داده",
        "SKILL_CAT_TOOLS": "ابزارها",
        # Per-page titles and meta descriptions. These were hardcoded Persian
        # in each template, so the English site served Persian <title> and
        # <meta description> tags on every page.
        "PAGE_HOME_TITLE": "امیرحسین نعیمائی | صفحه اصلی",
        "PAGE_HOME_DESC": "رزومه شخصی من شامل معرفی، پروژه‌ها، مهارت‌ها و راه‌های تماس.",
        "PAGE_ABOUT_TITLE": "امیرحسین نعیمائی | درباره من",
        "PAGE_ABOUT_DESC": "معرفی من، تخصص‌ها و تجربه‌های کاری در حوزه برنامه‌نویسی و طراحی وب.",
        "PAGE_PROJECTS_TITLE": "امیرحسین نعیمائی | پروژه‌ها",
        "PAGE_PROJECTS_DESC": "لیست پروژه‌های انجام‌شده در حوزه طراحی وب، نرم‌افزار و سیستم‌های هوشمند.",
        "PAGE_ARTICLES_TITLE": "مقالات و انتشارات",
        "PAGE_ARTICLES_DESC": "فهرست مقالات و انتشارات علمی امیرحسین نعیمائی در حوزه نرم‌افزار و هوش مصنوعی.",
        "PAGE_CONTACT_TITLE": "امیرحسین نعیمائی | تماس",
        "PAGE_CONTACT_DESC": "راه‌های تماس با من برای همکاری یا دریافت مشاوره در زمینه طراحی وب و نرم‌افزار.",
        "OG_HOME_TITLE": "رزومه من",
        "OG_HOME_DESC": "معرفی من، پروژه‌ها و مهارت‌های برنامه‌نویسی و طراحی وب.",
        "OG_PROJECTS_DESC": "مشاهده پروژه‌های طراحی وب و نرم‌افزار انجام‌شده توسط من.",
        "OG_CONTACT_DESC": "راه‌های ارتباطی برای همکاری و مشاوره در حوزه وب و نرم‌افزار.",
        # UI strings that were hardcoded or inlined as ternaries.
        "ABOUT_INTRO": "من یک توسعه‌دهندهٔ پایتون و Flask هستم که به ساخت سرویس‌های سریع و تمیز علاقه‌مندم.",
        "CURRENT": "هم‌اکنون",
        "THEME_TOGGLE": "تغییر حالت نمایش",
        "SCROLL_TOP": "بازگشت به بالا",
        "VIEW_ON_GITHUB": "مشاهده پروژه در GitHub",
        "VIEW_DETAILS": "مشاهده جزئیات",
        "ARTICLE_DETAILS": "جزئیات مقاله",
        "ABSTRACT": "چکیده مقاله",
        "DOWNLOAD_PDF": "دانلود PDF",
        "DOWNLOAD_PDF_FILE": "دانلود فایل PDF",
        "BACK_TO_ARTICLES": "بازگشت به لیست مقالات",
        "LANGUAGE_LABEL": "زبان:",
        "NO_ARTICLES": "مقاله‌ای ثبت نشده است.",
        "NO_PROJECTS": "پروژه‌ای ثبت نشده است.",
    },
    "en": {
        "SITE_TITLE": "My Resume",
        "NAME": "Amirhossein Naeimaei",
        "TAGLINE": "Backend Developer | Flask | Python",
        "META_DESCRIPTION": (
            "Resume and portfolio of Amirhossein Naeimaei, a Python backend "
            "developer focused on Flask, API design and databases."
        ),
        "MENU_HOME": "Home",
        "MENU_PROJECTS": "Projects",
        "MENU_ABOUT": "About",
        "MENU_ARTICLES": "Articles",
        "MENU_CONTACT": "Contact",
        "BTN_RESUME": "Download Resume",
        "BTN_PROJECTS": "See Projects",
        "CONTACT_TITLE": "Contact Me",
        "CONTACT_NAME": "Name",
        "CONTACT_EMAIL": "E-mail",
        "CONTACT_MSG": "Message",
        "CONTACT_SEND": "Send",
        "CONTACT_CLEAR": "Clear",
        "MSG_SUCCESS": "Your message has been sent successfully!",
        "MSG_ERROR": "Please fill in all fields.",
        "LOCATION": "Nowshahr",
        "SKILLS_TITLE": "Skills",
        "VIEWS": "views",
        "EXPERIENCE_TITLE": "Experience",
        "EDUCATION_TITLE": "Education",
        "ERR_404_TITLE": "Page not found",
        "ERR_404_BODY": "The page you were looking for does not exist or has moved.",
        "HERO_GREETING": "Hi, I'm",
        "HERO_SUFFIX": "",
        "HERO_ROLE": "IT Specialist & Software Developer",
        "HERO_INTRO": "I work across software development, IT infrastructure, networking and information systems, focused on building practical, scalable solutions.",
        "FOOTER_BIO": "Software developer and IT specialist, interested in practical system design, networking and emerging technology.",
        "STATUS_AVAILABLE": "Available for work",
        "QUICK_LINKS": "Quick links",
        "CONNECT": "Connect",
        "STAT_PROJECTS": "Projects",
        "STAT_ARTICLES": "Articles",
        "STAT_SKILLS": "Skills",
        "FEATURED_PROJECTS": "Featured projects",
        "LATEST_ARTICLES": "Latest articles",
        "VIEW_ALL": "View all",
        "PRIVATE_PROJECT": "Private project",
        "READ_ARTICLE": "Read article",
        "NO_PROJECTS_YET": "No projects yet.",
        "NO_ARTICLES_YET": "No articles published yet.",
        "NO_PROJECTS_TITLE": "No projects available",
        "NO_PROJECTS_BODY": "There are no projects to show yet.",
        "CTA_TITLE": "Have a project in mind?",
        "CTA_BODY": "If you'd like to talk about a project, a collaboration or anything technical, reach me through the contact page.",
        "BACK_TO_PROJECTS": "Back to projects",
        "STATUS_COMPLETED": "Completed",
        "STATUS_IN_PROGRESS": "In progress",
        "STATUS_PLANNED": "Planned",
        "ABOUT_PROJECT": "About this project",
        "KEY_FEATURES": "Key features",
        "PROJECT_INFO": "Project info",
        "LABEL_YEAR": "Year",
        "LABEL_STATUS": "Status",
        "TECHNOLOGIES": "Technologies",
        "SOURCE_CODE": "Source code",
        "VIEW_ON_GITHUB_SHORT": "View on GitHub",
        "LANG_FA": "Persian",
        "LANG_EN": "English",
        "ERR_429_TITLE": "Too many requests",
        "ERR_429_BODY": "You have sent too many requests. Please try again shortly.",
        "ERR_500_TITLE": "Server error",
        "ERR_500_BODY": "Something went wrong on our side. Please try again later.",
        "ERR_HOME": "Back to home",
        "SKILL_CAT_LANGUAGES": "Languages",
        "SKILL_CAT_FRAMEWORKS": "Frameworks",
        "SKILL_CAT_DATABASES": "Databases",
        "SKILL_CAT_TOOLS": "Tools",
        "PAGE_HOME_TITLE": "Amirhossein Naeimaei | Home",
        "PAGE_HOME_DESC": "My personal resume: introduction, projects, skills and contact details.",
        "PAGE_ABOUT_TITLE": "Amirhossein Naeimaei | About",
        "PAGE_ABOUT_DESC": "About me, my expertise and my professional experience in software development.",
        "PAGE_PROJECTS_TITLE": "Amirhossein Naeimaei | Projects",
        "PAGE_PROJECTS_DESC": "Projects I have built across web development, software and intelligent systems.",
        "PAGE_ARTICLES_TITLE": "Articles & Publications",
        "PAGE_ARTICLES_DESC": "List of published articles and papers by Amirhossein Naeimaei.",
        "PAGE_CONTACT_TITLE": "Amirhossein Naeimaei | Contact",
        "PAGE_CONTACT_DESC": "How to reach me for collaboration or consulting on web and software projects.",
        "OG_HOME_TITLE": "My Resume",
        "OG_HOME_DESC": "About me, my projects and my software development skills.",
        "OG_PROJECTS_DESC": "Web and software projects I have designed and built.",
        "OG_CONTACT_DESC": "Ways to get in touch for collaboration and consulting.",
        "ABOUT_INTRO": "I am a Python and Flask developer who enjoys building fast, clean services.",
        "CURRENT": "Present",
        "THEME_TOGGLE": "Toggle colour theme",
        "SCROLL_TOP": "Back to top",
        "VIEW_ON_GITHUB": "View project on GitHub",
        "VIEW_DETAILS": "View details",
        "ARTICLE_DETAILS": "View details",
        "ABSTRACT": "Abstract",
        "DOWNLOAD_PDF": "Download PDF",
        "DOWNLOAD_PDF_FILE": "Download PDF",
        "BACK_TO_ARTICLES": "Back to Articles",
        "LANGUAGE_LABEL": "Language:",
        "NO_ARTICLES": "No articles available.",
        "NO_PROJECTS": "No projects available.",
    },
}

DEFAULT_LANG = "fa"


EXPERIENCES = [
    {
        "year": "2021 - حالا",
        "year_en": "2021 - Present",
        "role": "توسعه‌دهندهٔ بک‌اند",
        "role_en": "Backend Developer",
        "company": "فریلنسر",
        "company_en": "Freelance",
        "desc": "توسعه و نگهداری سرویس‌های میکروسرویسی با Flask و Docker",
        "desc_en": "Building and maintaining microservices with Flask and Docker.",
        "stack": ["Python", "Flask", "Docker", "PostgreSQL", "Git"],
    },
    {
        "year": "2023 - حالا",
        "year_en": "2023 - Present",
        "role": "کارشناس شبکه و IT",
        "role_en": "Network & IT Specialist",
        "company": "هتل آراز",
        "company_en": "Araz Hotel",
        "desc": "مدیریت شبکه، CCTV و سیستم‌های تلفنی",
        "desc_en": "Managing networking, CCTV and telephony systems.",
        "stack": ["Linux", "Networking", "CCTV", "VoIP", "Windows Server"],
    },
]


EDUCATION = [
    {
        "year": "2018 - 2021",
        "degree": "دیپلم ریاضی و فیزیک",
        "degree_en": "High School Diploma, Mathematics & Physics",
        "university": "مدرسه شهید مدرس",
        "university_en": "Shahid Modarres High School",
        "desc": "تحصیل در رشته ریاضی و فیزیک",
        "desc_en": "Mathematics and physics track.",
    },
    {
        "year": "2021 - 2023",
        "degree": "فوق دیپلم نرم‌افزار",
        "degree_en": "Associate Degree, Software Engineering",
        "university": "دانشگاه آزاد اسلامی واحد چالوس",
        "university_en": "Islamic Azad University, Chalus Branch",
        "desc": "گرایش نرم‌افزار و برنامه‌نویسی",
        "desc_en": "Software and programming specialisation.",
    },
    {
        "year": "2023 - 2025",
        "degree": "کارشناسی مهندسی کامپیوتر",
        "degree_en": "B.Sc. Computer Engineering",
        "university": "دانشگاه آزاد اسلامی واحد چالوس",
        "university_en": "Islamic Azad University, Chalus Branch",
        "desc": "گرایش نرم‌افزار، پروژه پایانی در زمینهٔ یادگیری ماشین",
        "desc_en": "Software specialisation; final project on machine learning.",
    },
    {
        "year": "2025 - حالا",
        "year_en": "2025 - Present",
        "degree": "کارشناسی ارشد مدیریت سیستم‌های اطلاعاتی",
        "degree_en": "M.Sc. Information Systems Management",
        "university": "دانشگاه مارلیک نوشهر",
        "university_en": "Marlik University, Nowshahr",
        "desc": "در حال حاضر دانشجو، تمرکز بر مدیریت سیستم‌ها و تحلیل داده‌ها",
        "desc_en": "In progress; focused on systems management and data analysis.",
    },
]


# Shown in the footer the way brittanychiang.com credits its own stack —
# for a backend developer the site's own architecture is part of the pitch.
BUILT_WITH = ["Python", "Flask", "SQLAlchemy", "Jinja2", "Bootstrap", "Docker"]


SKILL_ICON_MAP = {
    "python": ("python", "3776AB"),
    "flask": ("flask", "64748b"),
    "javascript": ("javascript", "F7DF1E"),
    "js": ("javascript", "F7DF1E"),
    "django": ("django", "092E20"),
    "git": ("git", "F05032"),
    "git&github": ("git", "F05032"),
    "github": ("github", "181717"),
    "html": ("html5", "E34F26"),
    "html/css": ("html5", "E34F26"),
    "css": ("css3", "1572B6"),
    "sql": ("mysql", "4479A1"),
    "mysql": ("mysql", "4479A1"),
    "postgresql": ("postgresql", "4169E1"),
    "sqlite": ("sqlite", "003B57"),
    "sqlalchemy": ("sqlalchemy", "D71F00"),
    "docker": ("docker", "2496ED"),
    "react": ("react", "61DAFB"),
    "vue": ("vuedotjs", "4FC08D"),
    "linux": ("linux", "FCC624"),
    "nginx": ("nginx", "009639"),
    "redis": ("redis", "DC382D"),
    "typescript": ("typescript", "3178C6"),
    "bootstrap": ("bootstrap", "7952B3"),
    "tailwind": ("tailwindcss", "06B6D4"),
    "jinja2": ("jinja", "B41717"),
    "networking": ("cisco", "1BA0D7"),
    "voip": ("asterisk", "F60026"),
}


def get_skill_icon(name):
    icon, color = SKILL_ICON_MAP.get((name or "").strip().lower(), (None, "2563eb"))
    return {"icon": icon, "color": color}
