"""Add stack field to Project

Revision ID: f8d8eee5e8a1
Revises: 
Create Date: 2025-10-05 04:26:59.313690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d8eee5e8a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abouts')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stack', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('stack')

    op.create_table('abouts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('short_bio', sa.VARCHAR(length=300), nullable=True),
    sa.Column('full_bio', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=200), nullable=True),
    sa.Column('github', sa.VARCHAR(length=200), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
